### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by ThunderHen** [Alex-451/grayjay-media.ccc-plugin#1]
Any help would be appreciated.

From https://grayjay-sources.github.io/?nsfw
Opening [grayjay://plugin/https://raw.githubusercontent.com/Alex-451/grayjay-media.ccc-plugin/main/MediaCccConfig.json](grayjay://plugin/https://raw.githubusercontent.com/Alex-451/grayjay-media.ccc-plugin/main/MediaCccConfig.json)

Version information (version_name = 264, version_code = 264, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a12u, version-sdk = 31, version-os = samsung/a12usq/a12u:12/SP1A.210812.016/A125USQU6CWG2:user/release-keys)

(e, ExceptionActivity, 2024-09-14 08:38:54): Uncaught exception ("Unknown Context"): Illegal base64 character 3c

java.lang.IllegalArgumentException: Illegal base64 character 3c
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.futo.platformplayer.SignatureProvider$Companion.verify(SignatureProvider.kt:29)
	at com.futo.platformplayer.api.media.platforms.js.SourcePluginConfig.validate(SourcePluginConfig.kt:169)
	at com.futo.platformplayer.views.sources.SourceHeaderView.loadConfig(SourceHeaderView.kt:109)
	at com.futo.platformplayer.activities.AddSourceActivity.loadConfig(AddSourceActivity.kt:186)
	at com.futo.platformplayer.activities.AddSourceActivity.access$loadConfig(AddSourceActivity.kt:34)
	at com.futo.platformplayer.activities.AddSourceActivity$loadConfigUrl$1$4.invokeSuspend(AddSourceActivity.kt:177)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7ff46c, Dispatchers.IO]

**Comment by Alex-451** [comment]
Thanks for the report, I will take a look at the issue @ThunderHen

**Comment by ThunderHen** [comment]
After the last update it seems to be closer to installing seems to just be The plug-in script signature. 

Additionally, it would be nice if You could specify the domains that the plugin is allowed to use.
![](https://camo.githubusercontent.com/965b5575e7fed1b3bbcd9cc51cd24867b550401858cdcb9fb7f5f52a19faeb69/68747470733a2f2f706963616c6c6f772e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032352f30362f323032352d30362d32305f363835346661646264356663365f53637265656e73686f745f323032352d30362d31395f32332d30312d35322e706e67)
